{% set name = "ckanapi" %}
{% set version = "4.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ckanapi-{{ version }}.tar.gz
  sha256: 5691a7cb3d8ff42f16d800f8abd276e26dfd1cbe020103e5057e6179107f7263

build:
  noarch: python
  entry_points:
    - ckanapi = ckanapi.cli.main:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - setuptools
    - docopt
    - python-slugify >=1.0
    - requests
    - six >=1.9,<2.0
    - simplejson

test:
  imports:
    - ckanapi
  commands:
    - pip check
    - ckanapi --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ckan/ckanapi
  summary: A command line interface and Python module for accessing the CKAN Action API
  license: MIT
  license_file:
    - COPYING.fr
    - COPYING

extra:
  recipe-maintainers:
    - ocefpaf
