{% set version = "4.1" %}

package:
  name: ckanapi
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/ckanapi/ckanapi-{{ version }}.tar.gz
  sha256: b52cc659f436d5d226de9d40dbe6e30e930968f97d2f4138631dc00096101d9d

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - setuptools
    - docopt
    - requests
    - simplejson

test:
  imports:
    - ckanapi
    - ckanapi.cli
    - ckanapi.tests

about:
  home: https://github.com/ckan/ckanapi
  license: MIT
  # license_file: COPYING
  summary: 'A command line interface and Python module for accessing the CKAN Action API'

extra:
  recipe-maintainers:
    - ocefpaf
