{% set version = "4.3" %}

package:
  name: ckanapi
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/ckanapi/ckanapi-{{ version }}.tar.gz
  sha256: 4ce10a09ce995dd1b4bb5bad327e10a29c92059dc5014a631a43b7fb053008ce

build:
  number: 0
  entry_points:
    - ckanapi=ckanapi.cli.main:main
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python
    - pip
  run:
    - python
    - setuptools
    - docopt
    - python-slugify >=1.0,<2.0
    - requests
    - setuptools
    - six >=1.9,<2.0
    - simplejson  # [py27]

test:
  imports:
    - ckanapi
    - ckanapi.cli

about:
  home: https://github.com/ckan/ckanapi
  license: MIT
  license_file: COPYING
  summary: 'A command line interface and Python module for accessing the CKAN Action API'

extra:
  recipe-maintainers:
    - ocefpaf
