{% set version = "4.7" %}

package:
  name: ckanapi
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/ckanapi/ckanapi-{{ version }}.tar.gz
  sha256: 6cb1414faef384de58a0e1f648b977177db444e95073b65ed950f2a8b0f55d0d

build:
  number: 0
  noarch: python
  entry_points:
    - ckanapi=ckanapi.cli.main:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - setuptools
    - docopt
    - python-slugify >=1.0
    - requests
    - setuptools
    - six >=1.9,<2.0

test:
  imports:
    - ckanapi
    - ckanapi.cli
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ckan/ckanapi
  license: MIT
  license_file: COPYING
  summary: A command line interface and Python module for accessing the CKAN Action API

extra:
  recipe-maintainers:
    - ocefpaf
