{% set name = "ckanapi" %}
{% set version = "4.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ckanapi-{{ version }}.tar.gz
  sha256: 3a98d81e6cb7480883eb1d031740205d3e94176376e9d284d218829d81d0afed

build:
  noarch: python
  entry_points:
    - ckanapi = ckanapi.cli.main:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - setuptools
    - docopt
    - python-slugify >=1.0
    - requests
    - six >=1.9,<2.0
    - simplejson

test:
  imports:
    - ckanapi
  commands:
    - pip check
    - ckanapi --help
  requires:
    - pip

about:
  home: https://github.com/ckan/ckanapi
  summary: A command line interface and Python module for accessing the CKAN Action API
  license: MIT
  license_file:
    - COPYING.fr
    - COPYING

extra:
  recipe-maintainers:
    - ocefpaf
