travis:
  secure:
    BINSTAR_TOKEN: FrTIjLTAatcZtpAdGZjGnJP/p6hiVBG/tpgiE4PCfuV9D7+9VJak9Zdg+DhaNWSk6WgcPuswn1ucWjDeRXvTl3T2TlIdUy/fwg65EFaaoMd/WrB0bwy1b5jCcppw52qUjymOC5i37Mm4xwGE3AazK1KTPef0lk2e5zWvt0JBLlcL9EkUta8fsAGHcy08V1KEjCMJ165jTk0ZvAG5G39jAV5s0URCEmcOJWXptjb29YIN4ZwDTL3E+QPa47IG/9O9xIbz3J26YNESFG2oa3fH15V+C3lLvqAjJdEzvyoIJG+tLZR1aKfBONxUTMiuC3OBuHlOuMHzurp1/BnGUKE7TeqhUam7eRKUdPwj6vtuHiwyUh7m+jaGLg+SyKBaI5E15zoWycNLSPLGOppoy6o3V3gXZIQ4taEYVdXqqGt65ARAkvvQpL7283MTtFVSvQKJ/+NsglShZsYBHPL7Y1u4Gd4HyBJzHVbyfb+WKfejhAOuMiaQLrFvbZOw9PNE4Q1h6O2dpybsJn+ksvI0Q7T/xCLOQTDeYOqVNbfFWH6ln/AMYn8CYOho7ipT2Q6VWL+/n5gIWWY1KRJuU2K9myEdJYjEO5K281xxCjIPSTZAWiFcCK6f+L/F3yoLq81KBIIDluGrSTgzurFyufIZlpwVv7Oa2m3zIFiqGn4ZK9bSLHw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
