travis:
  secure:
    BINSTAR_TOKEN: VOQJWeAUVHSOuPhzgeJhLl4d2FtVn4hPe5spyKHKvO84jXzRwCfJalLi/RFgaauwgPvtq51jrJ9OwbFLN29sGTr+XcSrSWHI61wNdqAweQ5shpHQ78xIjNx+dzXAXGNUN3jyg0VpkRU5zQg7UB3l2H+oCk5l2yAb+eOk2fwSbvUgJXic33KZXhiCtmNO141di60gFpy2cTKGb3+DUG7BuA+I0rrTJRc4kOHuDDkOUVapyCZjGWqBW+YYb4ZKEZH+MfLlr7qBXqET7RosyvfocozBpFuxJqhyu3yor4mlNf0bwcNAKfChRbjGa0wnD1dOkBG4U9x60Qy7ucrnseu7pKEJR00Fk0EVdwZjD1ogXE2fxx/dX78TELtIAWiNTfMtH1gT9ga7Ic5M60Jy//ZqP1L7kRV2YM6p6OBCatKZMayJUYf4IBFh+OJ4L+0JYorua9/p1g4YOkPqcmkhKvuVbCzG1bmNyRiVE4+tdN8aiaGhIw629T011SFg531MNDWJGdQE9yKYmrPy9Zbky4IGMr3zYIxYIHSrD5XOKutF5m2IBJI+NbnMB6TzzTlSVi83R0eJ3i6zxIeXfR93q7xZf7lJl2LI2HdpyTYLWRTQT8jwLziftcI1qg9qXM3eXaPdI05O1XgqWFZy/VXewJ3UWqcUZAwCtfXyTiiTFtRGhR8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
